on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Source Code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/hngx-stage2-fastapi-book-project
            git pull origin main
            source /home/ubuntu/hngx-stage2-fastapi-book-project/venv/bin/activate  
            pip install -r requirements.txt
            sudo systemctl daemon-reload               
            sudo systemctl restart bookapi
            echo "Deployment complete!"
