on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Source Code
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/hngx-stage2-fastapi-book-project || exit 1
            git fetch origin main || exit 1
            git reset --hard origin/main || exit 1
            source /home/ubuntu/hngx-stage2-fastapi-book-project/venv/bin/activate || exit 1  
            pip install -r requirements.txt || exit 1
            sudo systemctl daemon-reload || exit 1                
            sudo systemctl restart bookapi || exit 1
            echo "Deployment complete!"
